apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
{{- if (regexFind "\\/|'|\\\\" .Values.password)  }}
  {{- fail "Passwords cannot contain the following symbols: \\ / ' " }}
{{- else }}
  MYSQL_ROOT_PASSWORD: {{ .Values.rootPassword | b64enc }}
  MYSQL_USER: {{ .Values.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.password | b64enc }}
  MYSQL_DATABASE: {{ .Values.database | b64enc }}
{{- end }}